
services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - project-database:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/projectschema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SECRETE: ${SECRETE}
      API_ACCESS_KEY: ${API_ACCESS_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/server-app
      - /server-app/node_modules

  health-connect:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server-app
    environment:
      - VITE_API_URL=http://server-app:7000
      - DOCKER_ENV=true
    volumes:
      - ./frontend:/health-connect
      - /health-connect/node_modules